on:
  # Runs on pushes targeting the default branch
  push:
    branches:
    - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3.5.2
     - name: Setup Node environemnt 
       uses: actions/setup-node@v2.5.2
       with:
         node-version: '18.x'
     - name: Setup Pages
       uses: actions/configure-pages@v3
     - name: Install dependencies
       run: npm i
     - name: Build storybook
       run: npm run build-storybook
     - name: Upload GitHub Pages artifact
       uses: actions/upload-pages-artifact@v1.0.8
       with:
         path: storybook-static
         
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v2.0.1
